id=org.coode.dlquery
version=${project.version}
download=https://repo1.maven.org/maven2/edu/stanford/protege/org.coode.dlquery/${project.version}/org.coode.dlquery-${project.version}.jar
name=DL Query
readme=https://github.com/protegeproject/dlquery/releases/tag/${project.version}
license=http://www.gnu.org/licenses/lgpl.html
author=Matthew Horridge
